### ISSUE TITLE
Always put properties before methods

### ISSUE THREAD

**Issue by codeliner** [open-code-modeling/php-code-ast#75]
When I have an existing value object with properties and getter methods and I want to add a new property + getter method, both property and method are added below existing code.

Would be nice if the new property gets added to list of properties and only the new method is added below other methods.

Is this possible?

**Comment by sandrokeil** [comment]
It should be possible but needs more effort. We have to sort the PhpParser visitors somehow. 

An easier solution would be to use [ClassBuilder::fromNodes()](https://github.com/open-code-modeling/php-code-ast/blob/0.13.x/src/Builder/ClassBuilder.php#L74) to load the current file AST and merge it somehow with the new `ClassBuilder`. But there may be some missing features, so code can be lost with this approach. 

At the moment the PhpParser visitors are added at the end, that's why new code is only added at the end of the class.

**Comment by sandrokeil** [comment]
I found an easy solution.
